### ISSUE TITLE
support custom redis instance

### ISSUE THREAD

**Issue by heeju** [abourdin/cache-flow#34]
Hello.
Redis support is great. However, Someone may need to Redis instance with their own configuration. 

for example Redis.Cluster
```js
import Redis from 'ioredis';
import { CacheFlow } from 'cache-flow';

const redisInstance = new Redis.Cluster({ 
  cluster: [
    {
      host: '1.1.1.1',
      port: 6379
    },
    {
      host: '1.1.1.2',
      port: 6379
    },
    ....
  ]
});

CacheFlow.configure({
  redisInstance // it replace configuration.redis
})
```

Is it possible to update for custom instance support?

**Comment by abourdin** [comment]
Hi @heeju, thanks for opening a ticket.

The difficulty here is that various NodeJS Redis libraries exist, and they do not expose the same API. Thus, they are not interchangeable. An option could be to explicitely support custom `ioredis` instances only, but that could be limiting as well.

Is your need specifically the support for a redis cluster configuration? Would the support for a cluster configuration be sufficient, for example:

```Javascript
CacheFlow.configure({
  redis: {
    cluster: [{
      host: '1.1.1.1',
      port: 6379
    },
    {
      host: '1.1.1.2',
      port: 6379
    }]
  }
})    
```

**Comment by abourdin** [comment]
@heeju I haven't heard from you in a while, should I close this ticket, or do you still have the need for this feature?

**Comment by heeju** [comment]
close please
